### ISSUE TITLE
Error: ffmpeg exited with code 1: Error configuring filter graph

### ISSUE THREAD

**Issue by oknoorap** [h2non/videoshow#42]
I got error when trying to this script (copied from https://github.com/h2non/videoshow/blob/master/examples/captions.js)

```
node index.js
ffmpeg process started: ffmpeg -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-4cbc73e2-53ac-4f0e-aaea-f0f007c8b20d -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-b3d807ab-b90a-415d-8780-52514baadd16 -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-ebcbe074-4099-4d29-abe2-17e258b179bf -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-cffb888b-8de6-4fe4-9c81-9835f7d4471b -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-d0d6a4c7-8a8a-4bae-ae89-1f11c3469967 -y -filter_complex concat=n=5:v=1:a=0 video.mp4
ffmpeg process started: ffmpeg -i C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-beab2652-1be8-4c75-8a6e-be2070d7b06c -y -vf subtitles='C:\Users\IAMCAP~1\AppData\Local\Temp\videoshow-20519391-39bb-43a5-81d2-60c33c4e2c52.ass' video.mp4
Error: Error: ffmpeg exited with code 1: Error configuring filter graph
Conversion failed!

    at ChildProcess.<anonymous> (D:\videotest\node_modules\fluent-ffmpeg\lib\processor.js:177:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

my code:
```javascript
const videoshow = require('videoshow')
const path = require('path')
const assetPath = path.join(__dirname, 'assets')
const binPath = path.join(__dirname, 'bin')

videoshow.ffmpeg.setFfmpegPath(path.join(binPath, 'ffmpeg.exe'))
videoshow.ffmpeg.setFfprobePath(path.join(binPath, 'ffprobe.exe')) 

const audio = path.join(assetPath, 'song.mp3')
const options = {
  loop: 5,
  captionDelay: 350,
  transition: true,
  useSubRipSubtitles: false,
  subtitleStyle: {
    Fontname: 'Verdana',
    Fontsize: '26',
    PrimaryColour: '11861244',
    SecondaryColour: '11861244',
    TertiaryColour: '11861244',
    BackColour: '-2147483640',
    Bold: '2',
    Italic: '0',
    BorderStyle: '2',
    Outline: '2',
    Shadow: '3',
    Alignment: '1',
    MarginL: '40',
    MarginR: '60',
    MarginV: '40'
  }
}

const images = [
  {
    path: path.join(assetPath, 'step_1.png'),
    caption: 'This is a sample subtitle'
  }, {
    path: path.join(assetPath, 'step_2.png'),
    caption: 'Another sample text',
    loop: 5
  }, {
    path: path.join(assetPath, 'step_3.png'),
    caption: 'Fast caption',
    captionStart: 2,
    captionEnd: 3
  }, {
    path: path.join(assetPath, 'step_4.png'),
    loop: 3
  }, {
    path: path.join(assetPath, 'step_5.png'),
    caption: 'Bye bye'
  }
]

videoshow(images, options)
.audio(audio)
.save('video.mp4')
.on('start', function (command) {
  console.log('ffmpeg process started:', command)
})
.on('error', function (err) {
  console.error('Error:', err)
})
.on('end', function (output) {
  console.log('Video created in:', output)
})
```

**Comment by h2non** [comment]
Try using `subrip`subtitles instead. See config options.

**Comment by oknoorap** [comment]
set `useSubRipSubtitles` to `true` right? it's still error.

**Comment by h2non** [comment]
The stop using Windows ;)
Or try limiting the flags passed to ffmpeg by hacking the package.

**Comment by reyesemf** [comment]
Excuseme please, i am trying to use this library but i have not look :(

Code:
`router.get('/', function(req, res, next) {
	var videoshow = require('videoshow')
	var folder = '/home/ereyes/dev/workspaces/viapais/video-generator/';
	var images = [
	  folder + 'media/1.jpg',
	  folder + 'media/2.jpg',
	  folder + 'media/3.jpg',
	  folder + 'media/4.jpg'
	]
	videoshow(images)
	  .save(folder + 'media/video.mp4')
	  .on('start', function (command) {
	    console.log('ffmpeg process started:', command)
	  })
	  .on('error', function (err) {
	    console.error('Error:', err)
	  })
	  .on('end', function (output) {
	    console.log('Video created in:', output)
	  })
  	res.render('index', { title: 'test' });
});`

Error:
`Error: [Error: ffmpeg exited with code 1: Error configuring complex filters.
Invalid argument
]
`

Can you help me?
