### ISSUE TITLE
Video Codec libx264 Not Found 

### ISSUE THREAD

**Issue by Jehanramadhan** [h2non/videoshow#52]
I have some code to make videoshow,
but when i running my script, i got this error :

```
jehan [images] Do > node index.js 
Error :  Error: Video codec libx264 is not available
    at /var/www/html/images/node_modules/fluent-ffmpeg/lib/capabilities.js:656:21
    at nextTask (/var/www/html/images/node_modules/async/dist/async.js:5297:14)
    at next (/var/www/html/images/node_modules/async/dist/async.js:5304:9)
    at /var/www/html/images/node_modules/async/dist/async.js:906:16
    at /var/www/html/images/node_modules/fluent-ffmpeg/lib/capabilities.js:484:7
    at handleExit (/var/www/html/images/node_modules/fluent-ffmpeg/lib/processor.js:170:11)
    at Socket.<anonymous> (/var/www/html/images/node_modules/fluent-ffmpeg/lib/processor.js:197:11)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)

```

**Comment by sebsebseb1982** [comment]
I've got the same problem. Do you have found a solution since ?
