### ISSUE TITLE
Captions example doesn't work

### ISSUE THREAD

**Issue by Huljo** [h2non/videoshow#70]
Hi, trying to use captions but the example provided doesn't work for me.

OS: Ubuntu 16.04.4 LTS
ffmpeg installed

> node example/captions.js

`
ffmpeg process started: ffmpeg -i /tmp/videoshow-b125f69d-eee3-4f45-88a4-096e61661544 -i /tmp/videoshow-c85a6426-715e-4248-a07d-c3f7b1c41d6e -i /tmp/videoshow-1f9f34a7-5c64-4c54-8350-36ac46a608f9 -i /tmp/videoshow-e0202044-23ee-4efb-a9fb-55969a2f1312 -i /tmp/videoshow-7923838d-d2c9-40f2-ae36-d9891e6db7d7 -y -filter_complex concat=n=5:v=1:a=0 video.mp4
ffmpeg process started: ffmpeg -i /tmp/videoshow-6a7f0f60-3f4f-4c45-a3a5-62258d1725b2 -i /home/joss/p/temp/videoshow/examples/../test/fixtures/song.mp3 -y -map 0:0 -map 1:0 -t 23 -af afade=t=in:ss=0:st=0:d=3 -af afade=t=out:st=20:d=3 -vf subtitles='/tmp/videoshow-490b9770-a7c7-4325-bd9a-1bb239857a0a.ass' video.mp4
Error: Error: ffmpeg exited with code 1: 
    at ChildProcess.<anonymous> (/home/joss/p/temp/videoshow/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
`

**Comment by mifi** [comment]
captionStart: 2,
    captionEnd: 3

should be milliseconds. maybe that's the problem

**Comment by MaximOrlovsky** [comment]
Solution from https://github.com/h2non/videoshow/issues/51#issuecomment-329579177 helped:
```
brew uninstall ffmpeg

brew install ffmpeg --with-chromaprint --with-fdk-aac --with-fontconfig --with-freetype --with-frei0r --with-game-music-emu --with-libass --with-libbluray --with-libbs2b --with-libcaca --with-libgsm --with-libmodplug --with-libsoxr --with-libssh --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openh264 --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-rubberband --with-schroedinger --with-sdl2 --with-snappy --with-speex --with-tesseract --with-theora --with-tools --with-two-lame --with-wavpack --with-webp --with-x265 --with-xz --with-zeromq --with-zimg
```
